from quickchart import QuickChart
import requests
import json
import discord


def create_chart(country):

    fetchUrl = "https://covidstats-backend-staging.herokuapp.com/bot"
    inputData = {"country": country.upper()}
    postReq = requests.post(fetchUrl, data=inputData)

    if postReq.status_code == 200:
        qc = QuickChart()
        qc.width = 1000
        qc.height = 700

        reqData = json.loads(postReq.text)["stats"]

        # Config can be set as a string or as a nested dict
        qc.config = {
            "type": 'bar',
            "data": {
                "labels": ["Cases", "Recovered", "Deaths"],
                "datasets": [{
                    "label": 'Statistics',
                    "data": [reqData["cases"], reqData["cured"], reqData["deaths"]],
                    "borderColor": "red",
                    "backgroundColor": "rgba(255, 0, 0, 0.7)",
                }]
            },
            "options": {
                "legend": {
                    "position": 'bottom',
                },
                "title": {
                    "display": "true",
                    "text": f'COVID Statistics for {reqData["country"]}',
                    "fontSize": 28,
                }
            }
        }
        covidEmbed = discord.Embed(
            title="COVID-19 Statistics for " + reqData["country"], color=0xdb0000)
        covidEmbed.set_thumbnail(url=reqData["flag"])
        covidEmbed.set_author(name="ADedicatedCoder", url="https://github.com/MahinKukreja",
                              icon_url="https://avatars.githubusercontent.com/u/40774998?s=400&v=4")
        covidEmbed.set_image(url=qc.get_url())
        covidEmbed.set_footer(
            text="Information provided by disease.sh - Open Disease Data API\nGraph generated by quickchart.io - QuickChart")

    else:
        covidEmbed = discord.Embed(
            title="Failure", description="Please double check spelling", color=0xbb0000)
        covidEmbed.set_thumbnail(
            url="https://cdn0.iconfinder.com/data/icons/shift-free/32/Error-512.png")
        covidEmbed.set_author(name="ADedicatedCoder", url="https://github.com/MahinKukreja",
                              icon_url="https://avatars.githubusercontent.com/u/40774998?s=400&v=4")
        covidEmbed.add_field(
            name="Error", value="Country not found", inline=False)
        covidEmbed.set_footer(
            text="Information provided by disease.sh - Open Disease Data API")
    return covidEmbed
