from quickchart import QuickChart
import requests
import json
import discord


def addCommas(num):
    return "{:,}".format(int(num))


def create_pie_chart(country):

    fetchUrl = "https://covidstats-backend-staging.herokuapp.com/bot"
    inputData = {"country": country.upper()}
    postReq = requests.post(fetchUrl, data=inputData)

    if postReq.status_code == 200:
        qc = QuickChart()
        qc.width = 500
        qc.height = 500

        reqData = json.loads(postReq.text)["stats"]

        # Config can be set as a string or as a nested dict
        qc.config = {
            "type": 'doughnut',
            "data": {
                "labels": ['Recovered', 'Deaths'],
                "datasets": [{
                    "data": [reqData["cured"], reqData["deaths"]],
                    "backgroundColor": ['rgb(75, 192, 192)', 'rgb(255, 205, 86)'],
                }]
            },
            "options": {
                "legend": {
                    "position": "bottom"
                },
                "title": {
                    "display": "true",
                    "text": f'COVID Statistics for {reqData["country"]}',
                    "fontSize": 36
                },
                "plugins": {
                    "datalabels": {
                        "display": "true",
                        "backgroundColor": '#ccc',
                        "borderRadius": 3,
                        "font": {
                            "color": 'green',
                            "weight": 'bold',
                        }
                    },
                    "doughnutlabel": {
                        "labels": [{
                            "text": addCommas(reqData["cases"]),
                            "font": {
                                "size": 24,
                                "weight": 'bold'
                            }
                        }, {
                            "text": 'Total Cases',
                            "font": {
                                "size": 14,
                            }
                        }]
                    }
                }
            }
        }
        covidEmbed = discord.Embed(
            title="COVID-19 Statistics for " + reqData["country"], color=0xdb0000)
        covidEmbed.set_thumbnail(url=reqData["flag"])
        covidEmbed.set_author(name="ADedicatedCoder", url="https://github.com/MahinKukreja",
                              icon_url="https://avatars.githubusercontent.com/u/40774998?s=400&v=4")
        covidEmbed.set_image(url=qc.get_short_url())
        covidEmbed.set_footer(
            text="Information provided by disease.sh - Open Disease Data API\nGraph generated by quickchart.io - QuickChart")

    else:
        covidEmbed = discord.Embed(
            title="Failure", description="Please double check spelling", color=0xbb0000)
        covidEmbed.set_thumbnail(
            url="https://cdn0.iconfinder.com/data/icons/shift-free/32/Error-512.png")
        covidEmbed.set_author(name="ADedicatedCoder", url="https://github.com/MahinKukreja",
                              icon_url="https://avatars.githubusercontent.com/u/40774998?s=400&v=4")
        covidEmbed.add_field(
            name="Error", value="Country not found", inline=False)
        covidEmbed.set_footer(
            text="Information provided by disease.sh - Open Disease Data API")
    return covidEmbed
